name: Backup and Clone

on:
  push:
    branches:
      - main

jobs:
  backup_and_clone:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: 3.132.85.71
        username: ubuntu
        key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
        port: 22

    - name: Backup data
      run: |
        sudo cp /var/www/html/.env /tmp
        sudo tar -czvf /tmp/backup.tar.gz /var/www/html/*
        sudo rm -rf /var/www/html/*

    - name: Clone data from GitHub
      uses: actions/checkout@v2
      with:
        ref: main
        path: /var/www/html

    - name: Move .env file back to directory
      run: |
        sudo mv /tmp/.env /var/www/html/.env

    - name: Run commands
      run: |
        cd /var/www/html
        composer install
        php artisan key:generate
        php artisan storage:link
        chmod -R 777 storage/
        chmod -R 777 bootstrap/
        php artisan optimize:clear
        sudo systemctl restart apache2
