# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# env:
#   ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Configure SSH key
#         uses: webfactory/ssh-agent@v0.4.0
#         with:
#           ssh-private-key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}

#       - name: Add SSH key to agent
#         run: |
#           echo "${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}" | ssh-add -

#       - name: Connect to EC2 instance
#         uses: appleboy/ssh-action@master
#         with:
#           host: 3.137.64.131
#           username: ubuntu
#           key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
#           port: 22
#           script: |
#             TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
#             cp /var/www/html/.env ~/backup
#             cd /var/www/html
#             tar -czvf backup_${TIMESTAMP}.tar.gz .
#             mv backup_${TIMESTAMP}.tar.gz ~/backup
#             sudo rm -rf /var/www/html/*

#             if git clone https://devmoweb:@github.com/Devmoweb/civilbook.git; then
#               mv civilbook/* .
#               rm -rf civilbook/
#               cp ~/backup/.env .
#               sudo chmod 664 .env
#             else
#               echo "An error occurred during clone process. Rolling back to previous backup..."
#               sudo rm -rf /var/www/html/*
#               tar -xzvf ~/backup/$(ls -t ~/backup | head -1) -C /var/www/html/
#               cp ~/backup/.env /var/www/html/
#               sudo chmod 664 /var/www/html/.env
#             fi

#             composer install
#             sudo php artisan key:generate
#             sudo php artisan storage:link
#             sudo chmod -R 777 storage/
#             sudo chmod -R 777 bootstrap/
#             sudo php artisan optimize:clear
#             sudo systemctl restart apache2
