name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
      - name: Add SSH key to agent
        run: ssh-add - <<< "${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}"
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 3.137.64.131
          username: ubuntu
          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          port: 22
          script: |
            cp /var/www/html/.env ~/backup
            cd /var/www/html
            tar -czvf backup.tar.gz .
            mv backup.tar.gz ~/backup
            sudo rm -rf /var/www/html/*
            git clone https://devmoweb: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@github.com/Devmoweb/civilbook.git
            mv civilbook/* .
            rm -rf civilbook/
            cp ~/backup/.env .
            sudo chmod 664 .env
            composer install
            sudo php artisan key:generate
            sudo php artisan storage:link
            sudo chmod -R 777 storage/
            sudo chmod -R 777 bootstrap/
            sudo php artisan optimize:clear
            sudo systemctl restart apache2          

            
          
      - name: Verify deployment
        run: |
          curl http://3.137.64.131	
